-- Run with a role permitted to create a database, schema and warehouse.
-- Choose a deliberately small warehouse; suspend it between exercises.
CREATE WAREHOUSE IF NOT EXISTS NORTHSTAR_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
CREATE DATABASE IF NOT EXISTS NORTHSTAR_FINANCE;
CREATE SCHEMA IF NOT EXISTS NORTHSTAR_FINANCE.RAW;
CREATE SCHEMA IF NOT EXISTS NORTHSTAR_FINANCE.ANALYTICS;
USE WAREHOUSE NORTHSTAR_WH;
USE DATABASE NORTHSTAR_FINANCE;
USE SCHEMA RAW;
CREATE FILE FORMAT IF NOT EXISTS NORTHSTAR_CSV TYPE = CSV FIELD_OPTIONALLY_ENCLOSED_BY = '"' SKIP_HEADER = 1 EMPTY_FIELD_AS_NULL = TRUE;
CREATE STAGE IF NOT EXISTS NORTHSTAR_STAGE FILE_FORMAT = NORTHSTAR_CSV;
CREATE TABLE IF NOT EXISTS EVENTS (EVENT_ID VARCHAR, TRANSACTION_ID VARCHAR, KIND VARCHAR, EVENT_DATE VARCHAR, AMOUNT_MINOR VARCHAR, CURRENCY VARCHAR);
CREATE TABLE IF NOT EXISTS SETTLEMENTS (LINE_ID VARCHAR, TRANSACTION_ID VARCHAR, PAYOUT_ID VARCHAR, SETTLED_DATE VARCHAR, GROSS_MINOR VARCHAR, FEE_MINOR VARCHAR, NET_MINOR VARCHAR, CURRENCY VARCHAR);
CREATE TABLE IF NOT EXISTS PAYOUTS (PAYOUT_ID VARCHAR, BANK_AMOUNT_MINOR VARCHAR, CURRENCY VARCHAR);
CREATE TABLE IF NOT EXISTS DISPUTES (DISPUTE_ID VARCHAR, TRANSACTION_ID VARCHAR, OPENED_DATE VARCHAR, AMOUNT_MINOR VARCHAR, STATUS VARCHAR);
