-- Upload files with Snowflake CLI or SnowSQL before executing COPY statements.
-- The PUT commands below run in a CLI client, not a Snowsight SQL worksheet.
-- Replace <ABSOLUTE_DATA_PATH> with the directory holding the four CSV files.
-- PUT file:///<ABSOLUTE_DATA_PATH>/events.csv @NORTHSTAR_FINANCE.RAW.NORTHSTAR_STAGE/events AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
-- PUT file:///<ABSOLUTE_DATA_PATH>/settlements.csv @NORTHSTAR_FINANCE.RAW.NORTHSTAR_STAGE/settlements AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
-- PUT file:///<ABSOLUTE_DATA_PATH>/payouts.csv @NORTHSTAR_FINANCE.RAW.NORTHSTAR_STAGE/payouts AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
-- PUT file:///<ABSOLUTE_DATA_PATH>/disputes.csv @NORTHSTAR_FINANCE.RAW.NORTHSTAR_STAGE/disputes AUTO_COMPRESS=TRUE OVERWRITE=TRUE;
USE WAREHOUSE NORTHSTAR_WH;
USE DATABASE NORTHSTAR_FINANCE;
USE SCHEMA RAW;
-- On a repeated load COPY skips already loaded staged file names by default.
-- Do not use FORCE=TRUE for an unchanged fixture; use a new path for a new batch.
COPY INTO EVENTS FROM @NORTHSTAR_STAGE/events FILE_FORMAT=(FORMAT_NAME=NORTHSTAR_CSV) ON_ERROR=ABORT_STATEMENT;
COPY INTO SETTLEMENTS FROM @NORTHSTAR_STAGE/settlements FILE_FORMAT=(FORMAT_NAME=NORTHSTAR_CSV) ON_ERROR=ABORT_STATEMENT;
COPY INTO PAYOUTS FROM @NORTHSTAR_STAGE/payouts FILE_FORMAT=(FORMAT_NAME=NORTHSTAR_CSV) ON_ERROR=ABORT_STATEMENT;
COPY INTO DISPUTES FROM @NORTHSTAR_STAGE/disputes FILE_FORMAT=(FORMAT_NAME=NORTHSTAR_CSV) ON_ERROR=ABORT_STATEMENT;
SELECT 'EVENTS' AS FEED, COUNT(*) AS ROW_COUNT FROM EVENTS
UNION ALL SELECT 'SETTLEMENTS', COUNT(*) FROM SETTLEMENTS
UNION ALL SELECT 'PAYOUTS', COUNT(*) FROM PAYOUTS
UNION ALL SELECT 'DISPUTES', COUNT(*) FROM DISPUTES;
